// img import
import ro1 from "../assets/images/blury-table-designify-4.png";
import ro2 from "../assets/images/sale-designify-1.png";
import ro3 from "../assets/images/blury-table-designify.png";
import ro4 from "../assets/images/blury-table-designify-2.webp";
import ro5 from "../assets/images/blury-table-designify-5.webp";
import ro6 from "../assets/images/blury-table-designify-6.webp";

// commercial import
import ro7 from "../assets/images/blury-table-designify-7.png";
import ro8 from "../assets/images/blury-table-designify-8.webp";
import ro9 from "../assets/images/blury-table-designify-9.webp";

// chimney import
import ro10 from "../assets/images/Chimney-e1702964936222.webp";
import ro11 from "../assets/images/Chimney-e1702964936222.webp";
import ro12 from "../assets/images/Chimney2-e1702964902990.webp";

export function priceToNumber(p) {
  if (!p) return 0;
  return parseInt(String(p).replace(/,/g, ""), 10) || 0;
}

export const domesticRO = [
  {
    id: "dom-1",
    name: "BlueGuard Camry Black",
    tech: "RO + UV + UF + TDS + Alkaline",
    img: ro1,
    category: "Domestic RO",
    badge: "Top Bestseller",
    rating: 4.9,
    reviews: 1240,
    price: "13,500",
    originalPrice: "18,500",
    numericPrice: 13500,
    tankCapacity: "8L",
    tdsLimit: "Up to 2000 ppm",
    mounting: "Wall Mount",
    features: ["Active Copper Technology", "Smart LED Monitor", "8L Storage Tank"],
  },
  {
    id: "dom-2",
    name: "BlueGuard Camry White",
    tech: "RO + UV + UF + TDS + Alkaline",
    img: ro2,
    category: "Domestic RO",
    badge: "Best Value",
    rating: 4.8,
    reviews: 980,
    price: "12,500",
    originalPrice: "16,500",
    numericPrice: 12500,
    tankCapacity: "8L",
    tdsLimit: "Up to 2000 ppm",
    mounting: "Wall Mount",
    features: ["Modular White Aesthetics", "Active Copper Mineral Guard", "Clear Level Gauge"],
  },
  {
    id: "dom-3",
    name: "BlueGuard Swift Plus",
    tech: "RO + UV + TDS + Alkaline",
    img: ro3,
    category: "Domestic RO",
    badge: "High Speed Purifier",
    rating: 4.9,
    reviews: 1120,
    price: "13,500",
    originalPrice: "17,990",
    numericPrice: 13500,
    tankCapacity: "10L",
    tdsLimit: "Up to 1500 ppm",
    mounting: "Wall Mount / Table Top",
    features: ["High-Pressure Swift Pump", "Copper + Zinc Mineral Cartridge", "Zero Tasteless Water"],
  },
  {
    id: "dom-4",
    name: "BlueGuard Grand Plus",
    tech: "RO + UV + TDS + Alkaline",
    img: ro4,
    category: "Domestic RO",
    badge: "Compact Choice",
    rating: 4.7,
    reviews: 860,
    price: "12,500",
    originalPrice: "16,000",
    numericPrice: 12500,
    tankCapacity: "12L",
    tdsLimit: "Up to 2000 ppm",
    mounting: "Wall Mount",
    features: ["Space-Saving 12L Tank", "Alkaline Mineral Boost", "Easy Filter Change"],
  },
  {
    id: "dom-5",
    name: "BlueGuard Pearl Plus",
    tech: "RO + UV + TDS + Alkaline",
    img: ro5,
    category: "Domestic RO",
    badge: "Premium Pick",
    rating: 4.8,
    reviews: 640,
    price: "15,500",
    originalPrice: "19,500",
    numericPrice: 15500,
    tankCapacity: "10L",
    tdsLimit: "Up to 2500 ppm",
    mounting: "Wall Mount",
    features: ["Elegant Pearl Finish", "UV + UV Double Protection", "Auto Shut-Off"],
  },
  {
    id: "dom-6",
    name: "BlueGuard Alfa Black",
    tech: "RO + UV + UF + TDS + Alkaline",
    img: ro6,
    category: "Domestic RO",
    badge: "Family Size",
    rating: 4.6,
    reviews: 540,
    price: "12,500",
    originalPrice: "15,900",
    numericPrice: 12500,
    tankCapacity: "12L",
    tdsLimit: "Up to 2000 ppm",
    mounting: "Wall Mount",
    features: ["12L Large Tank", "UV + UF Combo", "Matte Black Body"],
  },
  {
    id: "dom-7",
    name: "BlueGuard Nova Steel",
    tech: "RO + UV + UF + TDS",
    img: ro1,
    category: "Domestic RO",
    badge: "New Launch",
    rating: 4.7,
    reviews: 410,
    price: "14,900",
    originalPrice: "19,900",
    numericPrice: 14900,
    tankCapacity: "10L",
    tdsLimit: "Up to 2000 ppm",
    mounting: "Wall Mount",
    features: ["Steel-Finish Panel", "7-Stage Purification", "Smart Auto Flush"],
  },
  {
    id: "dom-8",
    name: "BlueGuard Aqua Mini",
    tech: "RO + UV",
    img: ro3,
    category: "Domestic RO",
    badge: "Budget Friendly",
    rating: 4.6,
    reviews: 320,
    price: "10,900",
    originalPrice: "13,900",
    numericPrice: 10900,
    tankCapacity: "6L",
    tdsLimit: "Up to 1000 ppm",
    mounting: "Wall Mount",
    features: ["Compact Wall-Mount Design", "RO + UV Purification", "6L Storage Tank"],
  },
  {
    id: "dom-9",
    name: "BlueGuard Royale Copper",
    tech: "RO + UV + UF + Copper + Alkaline",
    img: ro5,
    category: "Domestic RO",
    badge: "Editor's Choice",
    rating: 4.9,
    reviews: 275,
    price: "16,900",
    originalPrice: "21,900",
    numericPrice: 16900,
    tankCapacity: "10L",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Wall Mount",
    features: ["Ayurvedic Copper Charging", "9-Stage Purification", "10L Storage Tank"],
  },
  {
    id: "dom-10",
    name: "BlueGuard Tez 15",
    tech: "RO + UV + TDS",
    img: ro6,
    category: "Domestic RO",
    badge: "Fastest Fill",
    rating: 4.5,
    reviews: 198,
    price: "11,900",
    originalPrice: "14,900",
    numericPrice: 11900,
    tankCapacity: "8L",
    tdsLimit: "Up to 1500 ppm",
    mounting: "Wall Mount",
    features: ["15 LPH Fast Purification", "Slim Wall-Mount Body", "Auto Shut-Off"],
  },
];

export const commercialRO = [
  {
    id: "com-1",
    name: "BlueGuard 25 LPH RO",
    img: ro7,
    tech: "RO + UV + TDS",
    category: "Commercial RO",
    badge: "Office & Clinic Favorite",
    rating: 4.7,
    reviews: 210,
    price: "18,900",
    originalPrice: "24,900",
    numericPrice: 18900,
    tankCapacity: "Commercial Heavy Duty",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Free Standing / Floor",
    features: ["25 LPH Output", "Heavy-Duty Pump", "Auto Flush System"],
  },
  {
    id: "com-2",
    name: "BlueGuard 50/150 LPH RO",
    img: ro8,
    tech: "RO + UV + TDS",
    category: "Commercial RO",
    badge: "Institutional Grade",
    rating: 4.6,
    reviews: 140,
    price: "38,990",
    numericPrice: 38990,
    prices: [
      { label: "50 LPH", value: "38,990" },
      { label: "150 LPH", value: "70,500" },
    ],
    tankCapacity: "Commercial Heavy Duty",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Free Standing / Floor",
    features: ["Dual Capacity Options", "Industrial Grade Membrane", "24x7 Continuous Use"],
  },
  {
    id: "com-3",
    name: "BlueGuard 500/1000 LPH RO",
    img: ro9,
    tech: "RO + UV + TDS",
    category: "Commercial RO",
    badge: "Industrial Plant",
    rating: 4.8,
    reviews: 65,
    price: "1,30,000",
    numericPrice: 130000,
    prices: [
      { label: "500 LPH", value: "1,30,000" },
      { label: "1000 LPH", value: "1,95,000" },
    ],
    tankCapacity: "Commercial Heavy Duty",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Free Standing / Floor",
    features: ["Fully Automatic Control Panel", "Stainless Steel Frame", "Low Maintenance"],
  },
  {
    id: "com-4",
    name: "BlueGuard 100 LPH RO",
    img: ro7,
    tech: "RO + UV + TDS",
    category: "Commercial RO",
    badge: "Restaurant Favorite",
    rating: 4.7,
    reviews: 90,
    price: "45,000",
    originalPrice: "55,000",
    numericPrice: 45000,
    tankCapacity: "Commercial Heavy Duty",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Free Standing / Floor",
    features: ["100 LPH High Flow", "Commercial Grade Pump", "3-Year Warranty"],
  },
  {
    id: "com-5",
    name: "BlueGuard 250 LPH RO",
    img: ro8,
    tech: "RO + UV + TDS",
    category: "Commercial RO",
    badge: "Factory Grade",
    rating: 4.6,
    reviews: 54,
    price: "95,000",
    originalPrice: "1,15,000",
    numericPrice: 95000,
    tankCapacity: "Commercial Heavy Duty",
    tdsLimit: "Up to 3000 ppm",
    mounting: "Free Standing / Floor",
    features: ["250 LPH Output", "PLC Auto Control", "SS 304 Frame"],
  },
];

export const chimneys = [
  {
    id: "chim-1",
    name: "BlueGuard SC BK 60",
    tech: "Autoclean – Heat Auto Clean",
    img: ro10,
    category: "Kitchen Chimney",
    badge: "Top Rated",
    rating: 4.6,
    reviews: 320,
    price: "15,500",
    originalPrice: "19,900",
    numericPrice: 15500,
    tankCapacity: "N/A",
    tdsLimit: "N/A",
    mounting: "Wall Mounted Chimney",
    features: ["60cm Black Tempered Glass", "1200 m³/hr Suction", "Motion Sensor Touch Control"],
  },
  {
    id: "chim-2",
    name: "BlueGuard Novio",
    tech: "Autoclean – Heat Auto Clean",
    img: ro11,
    category: "Kitchen Chimney",
    badge: "Filter-less Design",
    rating: 4.7,
    reviews: 260,
    price: "14,990",
    originalPrice: "18,990",
    numericPrice: 14990,
    tankCapacity: "N/A",
    tdsLimit: "N/A",
    mounting: "Wall Mounted Chimney",
    features: ["60cm / 90cm Width Options", "Filter-less, 1200 m³/hr", "Touch / Motion Control"],
  },
  {
    id: "chim-3",
    name: "BlueGuard Feel 3D",
    tech: "Baffle Filter",
    img: ro12,
    category: "Kitchen Chimney",
    badge: "Curved Glass",
    rating: 4.5,
    reviews: 180,
    price: "12,450",
    originalPrice: "15,900",
    numericPrice: 12450,
    tankCapacity: "N/A",
    tdsLimit: "N/A",
    mounting: "Wall Mounted Chimney",
    features: ["Stainless Steel + Curved Glass", "1095 m³/hr Suction", "Baffle Filter"],
  },
  {
    id: "chim-4",
    name: "BlueGuard Crown 90",
    tech: "Autoclean – Heat Auto Clean",
    img: ro10,
    category: "Kitchen Chimney",
    badge: "90cm Wide Kitchen",
    rating: 4.8,
    reviews: 140,
    price: "17,500",
    originalPrice: "21,900",
    numericPrice: 17500,
    tankCapacity: "N/A",
    tdsLimit: "N/A",
    mounting: "Wall Mounted Chimney",
    features: ["90cm Wide Body", "1400 m³/hr Suction", "Motion Sensor Touch Control"],
  },
  {
    id: "chim-5",
    name: "BlueGuard Slimline 60",
    tech: "Autoclean – Heat Auto Clean",
    img: ro12,
    category: "Kitchen Chimney",
    badge: "Slim Profile",
    rating: 4.6,
    reviews: 110,
    price: "13,900",
    originalPrice: "17,500",
    numericPrice: 13900,
    tankCapacity: "N/A",
    tdsLimit: "N/A",
    mounting: "Wall Mounted Chimney",
    features: ["Ultra-Slim Body", "1100 m³/hr Suction", "Push Button Control"],
  },
];

export const roParts = [
  { id: "part-1", name: "Sediment Filter (Stage 1)", note: "Fits most RO models", price: "250", numericPrice: 250, category: "RO Parts & Accessories", tech: "Filter", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrg-3le2pyeVhCTfznnSCM9S6y4siqGrWF5sTMFqnrBQ&s=10", features: ["10 Micron Filtration", "Removes Mud & Rust"] },
  { id: "part-2", name: "Pre-Carbon Filter (Stage 2)", note: "Fits most RO models", price: "280", numericPrice: 280, category: "RO Parts & Accessories", tech: "Filter", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNnBqHfCQNd7yoCiBb85fLMUIuLZ9PTjEfVNV88iSAoA&s=10", features: ["Activated Charcoal", "Absorbs Chlorine & Odor"] },
  { id: "part-3", name: "Post-Carbon Filter", note: "Fits most RO models", price: "320", numericPrice: 320, category: "RO Parts & Accessories", tech: "Filter", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9MCd8b254ZAIQ7yme9pAXhMBCiYqfZYQ8lV7AmZIxPw&s=10", features: ["Enhances Taste", "Final Stage Polishing"] },
  { id: "part-4", name: "RO Membrane (80 GPD)", note: "Domestic purifiers", price: "1,450", numericPrice: 1450, category: "RO Parts & Accessories", tech: "RO", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBQVig2OGxGEEL2yAOSIagBb1l-pXHVHDZyJqoy-TIog&s", features: ["High Rejection Rate", "Durable Polymer Sheet"] },
  { id: "part-5", name: "RO Membrane (100 GPD)", note: "Domestic & light commercial", price: "1,650", numericPrice: 1650, category: "RO Parts & Accessories", tech: "RO", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHHpwCYJuWHOShhv2mP8mwpfOsTiR_7-GVYVIpbPFyiw&s=10", features: ["High Capacity Flow", "Removes Dissolved Salts"] },
  { id: "part-6", name: "SMPS Power Adapter", note: "Universal fit", price: "650", numericPrice: 650, category: "RO Parts & Accessories", tech: "Power", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIZpRH1g0snrcgq6yojwLziCK385VpvELYbWFt71NM2w&s", features: ["24V DC Output", "Over-Voltage Protection"] },
  { id: "part-7", name: "Booster Pump", note: "For low water pressure", price: "1,200", numericPrice: 1200, category: "RO Parts & Accessories", tech: "Pump", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1-DXM_M-fYFJnWCbLit6N3Y0--JGTSZfD2iY820nzAw&s=10", features: ["Heavy Duty Motor", "Silent Operation"] },
  { id: "part-8", name: "Solenoid Valve", note: "Fits most RO models", price: "350", numericPrice: 350, category: "RO Parts & Accessories", tech: "Valve", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlnJO43ibw1_5uGxC7UZXsViqehvf3ttdqrLznLRv8aw&s", features: ["Auto Water Cutoff", "100% Copper Coil"] },
  { id: "part-9", name: "Float Valve", note: "Storage tank fitting", price: "180", numericPrice: 180, category: "RO Parts & Accessories", tech: "Valve", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRa3jU-8-QD4H4sD6WMY3EKWbxRqM9lDIS-MBM0g57bOQ&s=10", features: ["Prevents Overflow", "Food Grade Plastic"] },
  { id: "part-10", name: "UV Lamp", note: "Standard 11W", price: "450", numericPrice: 450, category: "RO Parts & Accessories", tech: "UV", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBu06t57LDMZGa82wjh33wDrnclXG0N9kXdcw00lPN_w&s", features: ["Kills Bacteria & Viruses", "Long Lifespan"] },
  { id: "part-11", name: "Filter Housing (Set of 3)", note: "Universal fit", price: "600", numericPrice: 600, category: "RO Parts & Accessories", tech: "Housing", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaAv2CTRtoIdkDB8lv11jzJEOGiIvJ637x9Q8PYkinNw&s", features: ["Leak-proof O-ring", "Heavy Wall Thickness"] },
  { id: "part-12", name: "Annual Filter Kit", note: "All filters, 1-year supply", price: "1,999", numericPrice: 1999, category: "RO Parts & Accessories", tech: "Kit", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_TcAvGNfmJ6Lk8MN5u4YDKJ9efLftL_rLORqsYZvQcQ&s=10", features: ["Complete 1-Year Pack", "Includes Spanner & Fittings"] },
  { id: "part-13", name: "TDS Controller Valve", note: "Adjustable mineral balance", price: "420", numericPrice: 420, category: "RO Parts & Accessories", tech: "Valve", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRs2lAdN0lxoYeipnMoBkYSsPH6LLWA4wW7x4auohhQvA&s", features: ["Brass Metering Screw", "Precise TDS Tuning"] },
  { id: "part-14", name: "Inline Non-Return Valve", note: "Prevents backflow", price: "150", numericPrice: 150, category: "RO Parts & Accessories", tech: "Valve", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe8fYfeD8jcVfJnbKnDJGvpvt5QIDZYCfMQsVuqZPbhg&s=10", features: ["Push-Fit Connector", "Zero Leakage Design"] },
];

export const allTechs = ["RO", "UV", "UF", "Copper", "Alkaline", "TDS Control", "Heat Auto Clean"];

export const categories = [
  "All",
  "Domestic RO",
  "Commercial RO",
  "Kitchen Chimney",
  "RO Parts & Accessories",
];

export const tankCapacities = [
  "All",
  "6L",
  "8L",
  "10L",
  "12L",
  "Commercial Heavy Duty",
];

export const tdsLimits = [
  "All",
  "Up to 1000 ppm",
  "Up to 1500 ppm",
  "Up to 2000 ppm",
  "Up to 3000 ppm",
];

export const priceRanges = [
  { label: "All Prices", min: 0, max: Infinity },
  { label: "Under ₹2,000", min: 0, max: 2000 },
  { label: "₹2,000 - ₹12,000", min: 2000, max: 12000 },
  { label: "₹12,000 - ₹15,000", min: 12000, max: 15000 },
  { label: "₹15,000 - ₹30,000", min: 15000, max: 30000 },
  { label: "Above ₹30,000", min: 30000, max: Infinity },
];

